name: .Net Full Framework Build and Release to Windows Services
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  OUTPUT_DIRECTORY: c:\myapp
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true 
  SERVICE_NAME: SampleWindowsServicesGHA
  SERVICE_DIRECTORYNAME: C:\Services\ ${{ env.SERVICE_NAME }}
jobs:

  build:
    runs-on: self-hosted
    env:
      Solution_Name: 'SampleWindowsServicesGHA.sln'                      
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
    
    steps:    
    - name: Checkout
      uses: actions/checkout@v2      
      
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
      
    - name: Restore Packages
      run: nuget restore $env:Solution_Name
  
    - name: Setup MSbuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Build using MSBuild
      run: msbuild $env:Solution_Name /p:platform=$env:buildPlatform /p:Configuration=$env:buildConfiguration /p:OutputPath=${{ env.OUTPUT_DIRECTORY }}
      
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: windowsservices
        path: ${{ env.OUTPUT_DIRECTORY }}
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.7
      with:
        name:  windowsservices
    - name: Copy Windows Services files
      uses: canastro/copy-action@0.0.2
      with:
        source: ${{ github.workspace }}
        target: ${{ env.SERVICE_DIRECTORYNAME }}
